import React from "react";

export const adminStyles: Record<string, React.CSSProperties> = {
  primary: {
    background: "#F0EBE0",
    color: "#080808",
    border: "none",
    padding: "8px 18px",
    fontSize: "11px",
    fontWeight: 500,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    fontFamily: "'Inter', sans-serif",
    cursor: "pointer",
    transition: "opacity 0.2s ease",
  },
  accent: {
    background: "none",
    color: "#C4A46B",
    border: "1px solid rgba(196,164,107,0.4)",
    padding: "8px 18px",
    fontSize: "11px",
    fontWeight: 500,
    letterSpacing: "0.06em",
    fontFamily: "'Inter', sans-serif",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  select: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "rgba(240,235,224,0.8)",
    padding: "8px 12px",
    fontSize: "13px",
    fontFamily: "'Inter', sans-serif",
    outline: "none",
    cursor: "pointer",
    transition: "border-color 0.2s ease",
  },
  ghost: {
    background: "none",
    color: "rgba(240,235,224,0.5)",
    border: "1px solid rgba(255,255,255,0.08)",
    padding: "8px 14px",
    fontSize: "12px",
    fontFamily: "'Inter', sans-serif",
    letterSpacing: "0.02em",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  danger: {
    background: "none",
    color: "#f87171",
    border: "1px solid rgba(239,68,68,0.2)",
    padding: "8px 14px",
    fontSize: "12px",
    fontFamily: "'Inter', sans-serif",
    letterSpacing: "0.02em",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontSize: "11px",
    fontWeight: 500,
    color: "rgba(240,235,224,0.45)",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    fontFamily: "'Inter', sans-serif",
  },
  input: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "rgba(240,235,224,0.8)",
    padding: "8px 12px",
    fontSize: "13px",
    fontFamily: "'Inter', sans-serif",
    outline: "none",
    transition: "border-color 0.2s ease",
  },
};
